ERROR - 05/11/2024 21:17:48 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f6d2d416790>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:185)
INFO - 05/11/2024 21:21:09 : Index leak_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:173)
INFO - 05/11/2024 21:21:09 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
ERROR - 05/11/2024 21:56:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94c1fad0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:08 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bcb3d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bfd5d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9687c590>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:11 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95981650>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:11 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967e6e50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:11 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967ff310>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:12 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967e6210>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:12 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94c1ff90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:12 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd97527d10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:13 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd968659d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:13 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967e7850>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:13 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96883f90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:14 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cc210>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:22 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95917650>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:23 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94ba98d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:23 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc3a90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:23 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967e47d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:24 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bda890>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bcbe90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bbdf90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:29 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc0910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:29 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bdae50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:29 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9593ac50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b4abd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bcb410>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b98450>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bbda10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b54490>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b48550>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bcaa50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b49690>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc0610>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b98ad0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95915e50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b48e90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc0750>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:34 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b80050>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:34 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9593a850>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:35 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9593b5d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:35 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b48f50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:35 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b4b150>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc1610>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc2e10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959151d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95939910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc0dd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc07d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94beecd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96865a90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c2190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cf810>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96822b10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cebd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:40 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96865a90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b818d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cf2d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:45 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cec90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96880fd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96819b90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967ced50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:54 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967ce410>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95939b90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959d9090>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95917490>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:56:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95938f90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:00 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cc390>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:00 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc0710>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:01 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967bb750>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:01 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95914e10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:01 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959da450>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:02 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967ced50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:02 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95917c90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:02 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95914e50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:03 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95904e50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:03 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95906110>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:03 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cfa50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bba990>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc1510>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc1c10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:05 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94ba2790>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:05 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95916110>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959072d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95904b10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bedc50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:07 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95939150>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:07 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc0250>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:07 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959146d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:08 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c0ad0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:08 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cda90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:12 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95938bd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:13 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc3fd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:17 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c1810>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:17 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c2f10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:18 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd96877910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:18 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc2fd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:18 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c2d10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94c1d050>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:23 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95905890>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:27 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc1110>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95939190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bd8c50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bc3250>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:29 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cf850>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:29 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bdb090>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95983990>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cdf90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:30 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c2210>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bda390>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd92d7eb10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:31 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9593b690>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cc250>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:36 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94ba2590>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94ba2a90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bba190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967c2790>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd9593b190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959da450>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc2290>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95915fd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959d9790>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959daa10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd967cc450>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95906610>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd94bbbc90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95916890>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc1410>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc3c50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd959db5d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95916c10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:50 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc38d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95bc1ed0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95b4ab10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:57:55 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7efd95905f10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00adf06290>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:185)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a68d90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c288d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bd6fd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c00d50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c03490>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bce0d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bccd90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb1bd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb1890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bce1d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c009d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd6d10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd4bd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a9da10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:37 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd6510>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b82b50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b80850>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf7a50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b66750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c192d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c1b210>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b83890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b66150>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd4e50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd6890>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b64bd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b80b90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd5850>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b82d10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bcc4d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b82250>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd65d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf41d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b67d90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c00a90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:40 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b83ed0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:41 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b65510>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:44 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5356e90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:46 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf4b90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b561d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b82750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf7c50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:49 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b54ad0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bdbc50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a9f090>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b56e90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:53 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c1a450>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:53 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf4a90>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:56 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf4810>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:56 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bc5e50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:56 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b540d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:56 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a9d810>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:58 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f0039757cd0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:185)
ERROR - 05/11/2024 21:58:58 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bdb750>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:58:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf5c50>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:59:01 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b57a10>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:59:05 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c19690>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:59:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c03090>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:59:08 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b579d0>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 21:59:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b67410>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:15 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bcd5d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:20 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b823d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:20 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb1f90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:20 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c0d2d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:21 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd7550>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:21 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b67e10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:21 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c0ffd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:22 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c16a10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:22 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bccc10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:22 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b65a50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:27 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a8a010>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:27 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b57a90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:27 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bcf910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c1fe90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:28 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb2bd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:32 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c04910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b83d10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b81150>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:42 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf5790>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:42 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf4450>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:42 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b81390>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b83190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:51 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb2550>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:00:59 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a8a110>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b82cd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00adf071d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:04 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bfff50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:09 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bd4d10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b80ad0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b83750>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:10 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a82810>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c39ed0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b57150>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:19 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b80c10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:20 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a45370d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:20 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5c020d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:24 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf7cd0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:25 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf44d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8a81b50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:33 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c4a210>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:34 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf6210>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:38 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bcf8d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8bfff90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:39 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bf7e90>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:47 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bcc910>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:48 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5b81a10>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd5f50>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:52 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c1c090>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:53 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bcd490>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:57 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a8c406d0>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:01:57 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bb3190>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:02:06 : [1] Something unexpected happened while inserting : Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f00a5bd4850>: Failed to resolve 'elasticsearch' ([Errno -2] Name or service not known))) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:228)
ERROR - 05/11/2024 22:03:03 : ELASTIC 1 : Initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa199ccb310>: Failed to establish a new connection: [Errno 111] Connection refused)) - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:185)
INFO - 05/11/2024 22:06:51 : Created index: leak_model with mapping - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:171)
INFO - 05/11/2024 22:06:51 : Index generic_model already exists, skipping creation. - elastic_controller (/app/app_manager/elastic_manager/elastic_controller.py:182)
